export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_DISINFECTORS = 'GET_DISINFECTORS';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_USERS = 'SET_LOADING_USERS';
export const SET_LOADING_CHATS = 'SET_LOADING_CHATS';
export const SET_LOADING_CURRENT_CHAT = 'SET_LOADING_CURRENT_CHAT';
export const SET_LOADING_ANONS = 'SET_LOADING_ANONS';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const NEW_CHAT_CREATED = 'NEW_CHAT_CREATED';
export const GET_ALL_CHATS = 'GET_ALL_CHATS';
export const GET_CURRENT_CHAT = 'GET_CURRENT_CHAT';
export const GET_ANONS = 'GET_ANONS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const ADD_ANONS = 'ADD_ANONS';

// operator
export const GET_SORTED_ORDERS = 'GET_SORTED_ORDERS';
export const SET_LOADING_SORTED_ORDERS = 'SET_LOADING_SORTED_ORDERS';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';