export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PROFILES = 'GET_PROFILES';
export const GET_DISINFECTORS = 'GET_DISINFECTORS';
export const SET_LOADING = 'SET_LOADING';
export const SET_LOADING_USERS = 'SET_LOADING_USERS';
export const SET_LOADING_CHATS = 'SET_LOADING_CHATS';
export const SET_LOADING_CURRENT_CHAT = 'SET_LOADING_CURRENT_CHAT';
export const SET_LOADING_ANONS = 'SET_LOADING_ANONS';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS';
export const ADD_ORDER = 'ADD_ORDER';
export const GET_COMPLETE_ORDERS_IN_MONTH = 'GET_COMPLETE_ORDERS_IN_MONTH';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const GET_ALL_USERS = 'GET_ALL_USERS';

// chat
export const NEW_CHAT_CREATED = 'NEW_CHAT_CREATED';
export const GET_ALL_CHATS = 'GET_ALL_CHATS';
export const GET_CURRENT_CHAT = 'GET_CURRENT_CHAT';
export const GET_ANONS = 'GET_ANONS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const EDIT_MESSAGE = 'EDIT_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';
export const ADD_ANONS = 'ADD_ANONS';

// disinfector
export const GET_DISINFECTOR_MATERIALS = 'GET_DISINFECTOR_MATERIALS';
export const GET_DISINF_MONTH_STATS = 'GET_DISINF_MONTH_STATS';
export const LOADING_DISINF_STATS = 'LOADING_DISINF_STATS';
export const LOADING_CURRENT_DISINFECTOR = 'LOADING_CURRENT_DISINFECTOR';
export const LOADING_ADD_MATERIAL_EVENTS = 'LOADING_ADD_MATERIAL_EVENTS';
export const GET_DISINF_WEEK_STATS = 'GET_DISINF_WEEK_STATS';
export const GET_ADD_MATERIAL_EVENTS = 'GET_ADD_MATERIAL_EVENTS';

// operator
export const GET_SORTED_ORDERS = 'GET_SORTED_ORDERS';
export const SET_LOADING_SORTED_ORDERS = 'SET_LOADING_SORTED_ORDERS';
export const SET_LOADING_COMPLETE_ORDERS = 'SET_LOADING_COMPLETE_ORDERS';
export const SET_LOADING_REPEAT_ORDER = 'SET_LOADING_REPEAT_ORDER';
export const GET_ORDER_BY_ID = 'GET_ORDER_BY_ID';
export const GET_COMPLETE_ORDERS = "GET_COMPLETE_ORDERS";
export const GET_COMPLETE_ORDER_BY_ID = 'GET_COMPLETE_ORDER_BY_ID';
export const SET_LOADING_OPERATOR_STATS = 'SET_LOADING_OPERATOR_STATS';
export const GOT_STATS_FOR_OPERATOR = 'GOT_STATS_FOR_OPERATOR';
export const GET_REPEAT_ORDERS = 'GET_REPEAT_ORDERS';
export const GET_REPEAT_ORDER_FORM = 'GET_REPEAT_ORDER_FORM';

// ADMIN
export const SET_LOADING_ORDER_QUERIES_FOR_ADMIN = 'SET_LOADING_ORDER_QUERIES_FOR_ADMIN';
export const SET_LOADING_ADMIN_STATS = 'SET_LOADING_ADMIN_STATS';
export const SET_LOADING_DISINFECTORS = 'SET_LOADING_DISINFECTORS';
export const SET_LOADING_OPERATORS = 'SET_LOADING_OPERATORS';
export const LOADING_CLIENTS = 'LOADING_CLIENTS';
export const SET_LOADING_ADD_MATERIAL_EVENTS = 'SET_LOADING_ADD_MATERIAL_EVENTS';

export const GET_ORDER_QUERIES_FOR_ADMIN = 'GET_ORDER_QUERIES_FOR_ADMIN';
export const GET_ADMIN_MONTH_STATS = 'GET_ADMIN_MONTH_STATS';
export const GET_ADMIN_WEEK_STATS = 'GET_ADMIN_WEEK_STATS';
export const GET_ADV_STATS = 'GET_ADV_STATS';
export const GET_OPERATOR_STATS = 'GET_OPERATOR_STATS';
export const GET_ALL_DISINFECTORS_FOR_ADMIN = 'GET_ALL_DISINFECTORS_FOR_ADMIN';
export const GET_ALL_OPERATORS_FOR_ADMIN = 'GET_ALL_OPERATORS_FOR_ADMIN';
export const GET_ADD_MAT_EVENTS_MONTH = 'GET_ADD_MAT_EVENTS_MONTH';
export const GET_ADD_MAT_EVENTS_WEEK = 'GET_ADD_MAT_EVENTS_WEEK';
export const ADD_MAT_DISINFECTOR = 'ADD_MAT_DISINFECTOR';
export const DISINF_STATS_MONTH_ADMIN = 'DISINF_STATS_MONTH_ADMIN';
export const DISINF_STATS_MONTH_WEEK = 'DISINF_STATS_MONTH_WEEK';
export const GET_CURR_MAT_ADMIN = 'GET_CURR_MAT_ADMIN';
export const LOADING_CUR_MAT = 'LOADING_CUR_MAT';
export const UPDATE_MAT_COMING = 'UPDATE_MAT_COMING';
export const MAT_COMING_MONTH = 'MAT_COMING_MONTH';
export const MAT_COMING_WEEK = 'MAT_COMING_WEEK';
export const SEARCH_CLIENTS = 'SEARCH_CLIENTS';

export const LOADING_SORTED_ORDERS_ADMIN = 'LOADING_SORTED_ORDERS_ADMIN';
export const GET_SORTED_ORDERS_ADMIN = 'GET_SORTED_ORDERS_ADMIN';

// Subadmin
export const GET_SORTED_ORDERS_SUBADMIN = 'GET_SORTED_ORDERS_SUBADMIN';
export const LOADING_SORTED_ORDERS_SUBADMIN = 'LOADING_SORTED_ORDERS_SUBADMIN';